include_guard()

list(
  APPEND
  JCM_DEFAULT_COMPILE_OPTIONS_GNU
  -Wall
  -Wextra
  -Wpedantic
  -Wconversion
  -Wsign-conversion
  -Weffc++)

list(APPEND JCM_DEFAULT_COMPILE_OPTIONS_CLANG ${JCM_DEFAULT_COMPILE_OPTIONS_GNU})

list(APPEND JCM_DEFAULT_COMPILE_OPTIONS_MSVC /W4 /WX)

string(CONCAT JCM_DEFAULT_COMPILE_OPTIONS
  "$<$<CXX_COMPILER_ID:GNU>:${JCM_DEFAULT_COMPILE_OPTIONS_GNU}>"
  "$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:"
  "${JCM_DEFAULT_COMPILE_OPTIONS_CLANG}>"
  "$<$<CXX_COMPILER_ID:MSVC>:"
  "${JCM_DEFAULT_COMPILE_OPTIONS_MSVC}>")
