include_guard()

list(
  APPEND
  JGD_DEFAULT_COMPILE_OPTIONS_GNU
  -Wall
  -Wextra
  -Wpedantic
  -Wconversion
  -Wsign-conversion
  -Weffc++)

list(APPEND JGD_DEFAULT_COMPILE_OPTIONS_CLANG ${JGD_DEFAULT_COMPILE_OPTIONS_GNU})

list(APPEND JGD_DEFAULT_COMPILE_OPTIONS_MSVC /W4 /WX)

string(CONCAT JGD_DEFAULT_COMPILE_OPTIONS
  "$<$<CXX_COMPILER_ID:GNU>:"
  "${JGD_DEFAULT_COMPILE_OPTIONS_GNU}>"
  "$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:"
  "${JGD_DEFAULT_COMPILE_OPTIONS_CLANG}>>"
  "$<$<CXX_COMPILER_ID:MSVC>:"
  "${JGD_DEFAULT_COMPILE_OPTIONS_MSVC}>")