set(JGD_PROJECT_CMAKE_DIR "${PROJECT_SOURCE_DIR}/cmake")
set(JGD_PROJECT_DATA_DIR "${PROJECT_SOURCE_DIR}/data")
set(JGD_PROJECT_TESTS_DIR "${PROJECT_SOURCE_DIR}/tests")
set(JGD_PROJECT_DOCS_DIR "${PROJECT_SOURCE_DIR}/docs")
