name: jgd-cmake-modules

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1
      - name: Install Doxygen for tests
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Configure tests target
        run: cmake --preset tests-ninja
      - name: Run all automated tests
        run: ctest --preset tests
