name: JCM CI (MacOS)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/pages.yaml
      - .github/workflows/ubuntu.yaml
      - .github/workflows/windows.yaml
      - docs/**
    branches:
      - main
  pull_request:
    paths-ignore:
      - .github/workflows/pages.yaml
      - .github/workflows/ubuntu.yaml
      - .github/workflows/windows.yaml
      - docs/**
    branches:
      - main
jobs:
  build-test-mac:
    runs-on: macos-12
    strategy:
      matrix:
        generator: ["Ninja"]
    # apple-clang doesn't support one-ranges proposal, which
    # is used in automated tests. Not concerned with test C/C++ code, just CMake.
    env:
      CC: gcc-11
      CXX: g++-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ninja-build
        if: ${{ matrix.generator }} == "Ninja"
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1
      - name: Install Doxygen & clang-format for tests
        run: brew install doxygen clang-format
      - name: Configure tests target
        run: cmake -G "${{ matrix.generator }}" --preset tests-ninja
      - name: Format test code to ignore formatting errors
        run: >
          clang-format --style=file -i
          $(find tests -name "*.hpp" -o -name "*.cpp" -o -name "*.h" -o -name "*.c")
      - name: Run all automated tests
        run: ctest --preset test-to-fail
