name: Deploy to GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1
      - name: Install Sphinx
        run: pip install -r sphinx-requirements.txt
      - name: Configure documentation generation
        run: cmake --preset docs-ninja
      - name: Build documentation
        run: cmake --build --preset sphinx-docs
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/docs/sphinx'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1