name: Docs on GH Pages

env:
  push_deploy_branch: main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/macos.yaml
      - .github/workflows/ubuntu.yaml
      - .github/workflows/windows.yaml
    branches:
      - main
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yaml
      - .github/workflows/ubuntu.yaml
      - .github/workflows/windows.yaml
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1
      - name: Install Sphinx
        run: pip install -r sphinx-requirements.txt
      - name: Configure documentation generation
        run: cmake --preset docs-ninja
      - name: Build documentation
        run: cmake --build --preset sphinx-docs
      - name: Upload artifact
        if: github.ref_name == env.push_deploy_branch && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build/docs/sphinx"
  deploy:
    # can't use env @ workflow level. Duplicate 'if' on each step
    # https://github.com/actions/runner/issues/480
    if: github.ref_name == env.push_deploy_branch && github.event_name == 'push'
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        if: github.ref_name == env.push_deploy_branch && github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v1
