name: jgd-cmake-modules

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install GCC with C++20
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - name: Install ninja-build and cmake
        uses: lukka/get-cmake@v.3.23.2
      - name: Install Doxygen for tests
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Install Python for documentation
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          pip install -r sphinx-requirements.txt
      - name: Configure all targets
        run: |
          which python
          cmake --preset all-ninja
      - name: Run all automated tests
        run: |
          ctest --preset tests
      - name: Build documentation
        run: |
          cmake --build --preset all-ninja
