name: JCM CI (Windows)

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/macos.yaml
      - .github/workflows/pages.yaml
      - .github/workflows/ubuntu.yaml
      - docs/
    branches:
      - main
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yaml
      - .github/workflows/pages.yaml
      - .github/workflows/ubuntu.yaml
      - docs/
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build-test-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        generator: ["Ninja", "Visual Studio 17 2022"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ninja-build
        if: ${{ matrix.generator }} == "Ninja"
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1
      - name: Install Doxygen for tests
        run: for i in 1 2 3; do choco install doxygen.install && break; done # multiple attempts
      - name: Configure tests target
        run: cmake -G "${{ matrix.generator }}" --preset tests-ninja
      - name: Format test code to ignore formatting errors
        run: >
          clang-format --style=file -i
          $(find tests -name "*.hpp" -o -name "*.cpp" -o -name "*.h" -o -name "*.c")
      - name: Run all automated tests
        run: ctest --preset test-to-fail
